/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controladores.ControladorVentanaPrincipal;
import javax.swing.JPanel;

/**
 *
 * @author SrKil
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private ControladorVentanaPrincipal controlador = new ControladorVentanaPrincipal();
     
    /**
     * Creates new form PaginaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAnyadirTarea = new javax.swing.JDialog();
        jLabelAnyadirTarea = new javax.swing.JLabel();
        jTextFieldAnyadirTarea = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        scrollPanelTareasEntrada = new javax.swing.JScrollPane();
        panelTareasEntrada = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        etiquetaUsuario = new javax.swing.JLabel();
        logoGTD = new javax.swing.JLabel();
        etiquetaAjustes = new javax.swing.JLabel();
        botonProcesar = new javax.swing.JButton();
        jButtonAbrirAnadirTarea = new javax.swing.JButton();
        jTextFieldNombreTareaEntrada = new javax.swing.JTextField();
        jLabelNombreTareaEntrada = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jDialogAnyadirTarea.setSize(new java.awt.Dimension(400, 213));

        jLabelAnyadirTarea.setText("Introduzca el Nombre de la nueva Tarea");

        jTextFieldAnyadirTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnyadirTareaActionPerformed(evt);
            }
        });
        jTextFieldAnyadirTarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAnyadirTareaKeyPressed(evt);
            }
        });

        jButton1.setText("Añadir Tarea");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogAnyadirTareaLayout = new javax.swing.GroupLayout(jDialogAnyadirTarea.getContentPane());
        jDialogAnyadirTarea.getContentPane().setLayout(jDialogAnyadirTareaLayout);
        jDialogAnyadirTareaLayout.setHorizontalGroup(
            jDialogAnyadirTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAnyadirTareaLayout.createSequentialGroup()
                .addGroup(jDialogAnyadirTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAnyadirTareaLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabelAnyadirTarea))
                    .addGroup(jDialogAnyadirTareaLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton1))
                    .addGroup(jDialogAnyadirTareaLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jTextFieldAnyadirTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jDialogAnyadirTareaLayout.setVerticalGroup(
            jDialogAnyadirTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAnyadirTareaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelAnyadirTarea)
                .addGap(37, 37, 37)
                .addComponent(jTextFieldAnyadirTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        panelTareasEntrada.setPreferredSize(new java.awt.Dimension(800, 2000));

        javax.swing.GroupLayout panelTareasEntradaLayout = new javax.swing.GroupLayout(panelTareasEntrada);
        panelTareasEntrada.setLayout(panelTareasEntradaLayout);
        panelTareasEntradaLayout.setHorizontalGroup(
            panelTareasEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        panelTareasEntradaLayout.setVerticalGroup(
            panelTareasEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        scrollPanelTareasEntrada.setViewportView(panelTareasEntrada);

        tabbedPane.addTab("Tareas entrada", scrollPanelTareasEntrada);

        etiquetaUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etiquetaUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaUsuario.setText("Usuario");

        logoGTD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fotoLogin.png"))); // NOI18N

        etiquetaAjustes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiquetaAjustes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaAjustes.setText("Ajustes");
        etiquetaAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiquetaAjustesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiquetaAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoGTD)))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoGTD, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaAjustes)
                .addGap(25, 25, 25))
        );

        botonProcesar.setText("Procesar");
        botonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProcesarActionPerformed(evt);
            }
        });

        jButtonAbrirAnadirTarea.setText("Añadir");
        jButtonAbrirAnadirTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirAnadirTareaActionPerformed(evt);
            }
        });

        jLabelNombreTareaEntrada.setText("Nombre de la tarea: ");

        jLabel1.setText("AÑADIR TAREAS DE ENTRADA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAbrirAnadirTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabelNombreTareaEntrada)
                        .addGap(37, 37, 37)
                        .addComponent(jTextFieldNombreTareaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonProcesar)))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAbrirAnadirTarea)
                    .addComponent(jTextFieldNombreTareaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreTareaEntrada))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProcesarActionPerformed
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vista.VentanaProcesamiento dialog = new vista.VentanaProcesamiento(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_botonProcesarActionPerformed

    private void jButtonAbrirAnadirTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirAnadirTareaActionPerformed
        panelTareasEntrada.add(controlador.crearPanelTareaEntrada(jTextFieldNombreTareaEntrada.getText()));
        panelTareasEntrada.updateUI();
    }//GEN-LAST:event_jButtonAbrirAnadirTareaActionPerformed

    private void jTextFieldAnyadirTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnyadirTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnyadirTareaActionPerformed

    private void jTextFieldAnyadirTareaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnyadirTareaKeyPressed
        
    }//GEN-LAST:event_jTextFieldAnyadirTareaKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void etiquetaAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaAjustesMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaAjustes dialog = new VentanaAjustes(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_etiquetaAjustesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonProcesar;
    private javax.swing.JLabel etiquetaAjustes;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAbrirAnadirTarea;
    private javax.swing.JDialog jDialogAnyadirTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAnyadirTarea;
    private javax.swing.JLabel jLabelNombreTareaEntrada;
    private javax.swing.JTextField jTextFieldAnyadirTarea;
    private javax.swing.JTextField jTextFieldNombreTareaEntrada;
    private javax.swing.JLabel logoGTD;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panelTareasEntrada;
    private javax.swing.JScrollPane scrollPanelTareasEntrada;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
