/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controladores.ControladorVentanaProcesamiento;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Dell
 */
public class VentanaProcesamiento extends javax.swing.JDialog {

    /**
     * Creates new form VentanaProcesamiento
     * @param parent
     * @param modal
     */
    
    private ControladorVentanaProcesamiento miControlador;
    public VentanaProcesamiento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        miControlador= new ControladorVentanaProcesamiento(this);
     
       
        
     
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabelTarea = new javax.swing.JLabel();
        jTextFieldTarea = new javax.swing.JTextField();
        jLabelDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDesc = new javax.swing.JTextArea();
        jLabelPrioridad = new javax.swing.JLabel();
        jComboBoxPrioridad = new javax.swing.JComboBox<>();
        jPanelComplejidad = new javax.swing.JPanel();
        jRadioButtonFacil = new javax.swing.JRadioButton();
        jRadioButtonMedia = new javax.swing.JRadioButton();
        jRadioButtonDificil = new javax.swing.JRadioButton();
        jRadioButtonLlora = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelFechaFin = new javax.swing.JPanel();
        jLabelF_Inicio = new javax.swing.JLabel();
        jTextFieldF_Inicio = new javax.swing.JTextField();
        jLabelF_FIn = new javax.swing.JLabel();
        jTextFieldF_Fin = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setFrameIcon(null);
        jInternalFrame1.setVisible(true);

        jLabelTarea.setText("Tarea");

        jTextFieldTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTareaActionPerformed(evt);
            }
        });

        jLabelDesc.setText("Descripción:");

        jTextAreaDesc.setColumns(20);
        jTextAreaDesc.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDesc);

        jLabelPrioridad.setText("Prioridad");

        jComboBoxPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgente", "Delegada", "Inmediata" }));
        jComboBoxPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPrioridadActionPerformed(evt);
            }
        });

        jPanelComplejidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Complejidad"));

        jRadioButtonFacil.setText("Facil");
        jRadioButtonFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFacilActionPerformed(evt);
            }
        });

        jRadioButtonMedia.setText("Media");
        jRadioButtonMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMediaActionPerformed(evt);
            }
        });

        jRadioButtonDificil.setText("Dificil");
        jRadioButtonDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDificilActionPerformed(evt);
            }
        });

        jRadioButtonLlora.setText("Llora");
        jRadioButtonLlora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLloraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelComplejidadLayout = new javax.swing.GroupLayout(jPanelComplejidad);
        jPanelComplejidad.setLayout(jPanelComplejidadLayout);
        jPanelComplejidadLayout.setHorizontalGroup(
            jPanelComplejidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComplejidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComplejidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonFacil)
                    .addComponent(jRadioButtonMedia)
                    .addComponent(jRadioButtonDificil)
                    .addComponent(jRadioButtonLlora))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanelComplejidadLayout.setVerticalGroup(
            jPanelComplejidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComplejidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonFacil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonMedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDificil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonLlora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFechaFin.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Finalizacion"));

        jLabelF_Inicio.setText("Inicio");

        jLabelF_FIn.setText("Fin");

        javax.swing.GroupLayout jPanelFechaFinLayout = new javax.swing.GroupLayout(jPanelFechaFin);
        jPanelFechaFin.setLayout(jPanelFechaFinLayout);
        jPanelFechaFinLayout.setHorizontalGroup(
            jPanelFechaFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFechaFinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFechaFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldF_Inicio)
                    .addGroup(jPanelFechaFinLayout.createSequentialGroup()
                        .addGroup(jPanelFechaFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelF_Inicio)
                            .addComponent(jLabelF_FIn))
                        .addGap(0, 147, Short.MAX_VALUE))
                    .addComponent(jTextFieldF_Fin))
                .addContainerGap())
        );
        jPanelFechaFinLayout.setVerticalGroup(
            jPanelFechaFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFechaFinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelF_Inicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldF_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelF_FIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldF_Fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonGuardar)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(jLabelPrioridad)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81)
                            .addComponent(jPanelComplejidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanelFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jSeparator1)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelTarea)
                                .addComponent(jLabelDesc))
                            .addGap(86, 86, 86)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldTarea)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTarea)
                    .addComponent(jTextFieldTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDesc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelComplejidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addComponent(jButtonGuardar)
                        .addContainerGap())
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrioridad))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTareaActionPerformed
       miControlador.tarea();
    }//GEN-LAST:event_jTextFieldTareaActionPerformed

    private void jRadioButtonFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFacilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFacilActionPerformed

    private void jRadioButtonMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMediaActionPerformed

    private void jRadioButtonDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDificilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDificilActionPerformed

    private void jRadioButtonLloraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLloraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLloraActionPerformed

    private void jComboBoxPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPrioridadActionPerformed
        miControlador.ComplejidadYFecha();
    }//GEN-LAST:event_jComboBoxPrioridadActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaProcesamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaProcesamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaProcesamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaProcesamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxPrioridad;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelF_FIn;
    private javax.swing.JLabel jLabelF_Inicio;
    private javax.swing.JLabel jLabelPrioridad;
    private javax.swing.JLabel jLabelTarea;
    private javax.swing.JPanel jPanelComplejidad;
    private javax.swing.JPanel jPanelFechaFin;
    private javax.swing.JRadioButton jRadioButtonDificil;
    private javax.swing.JRadioButton jRadioButtonFacil;
    private javax.swing.JRadioButton jRadioButtonLlora;
    private javax.swing.JRadioButton jRadioButtonMedia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaDesc;
    private javax.swing.JTextField jTextFieldF_Fin;
    private javax.swing.JTextField jTextFieldF_Inicio;
    private javax.swing.JTextField jTextFieldTarea;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getjComboBoxPrioridad() {
        return jComboBoxPrioridad;
    }

    public JPanel getjPanelComplejidad() {
        return jPanelComplejidad;
    }

    public JPanel getjPanelFechaFin() {
        return jPanelFechaFin;
    }

    public JRadioButton getjRadioButtonDificil() {
        return jRadioButtonDificil;
    }

    public JRadioButton getjRadioButtonFacil() {
        return jRadioButtonFacil;
    }

    public JRadioButton getjRadioButtonLlora() {
        return jRadioButtonLlora;
    }

    public JRadioButton getjRadioButtonMedia() {
        return jRadioButtonMedia;
    }

    public JTextArea getjTextAreaDesc() {
        return jTextAreaDesc;
    }

    public JTextField getjTextFieldF_Fin() {
        return jTextFieldF_Fin;
    }

    public JTextField getjTextFieldF_Inicio() {
        return jTextFieldF_Inicio;
    }

    public JTextField getjTextFieldTarea() {
        return jTextFieldTarea;
    }

    

}
